spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
  application:
    name: expressway
springdoc:
  default-produces-media-type: application/json
server:
  dtdc:
    check-serviceable: https://ebookingbackend.dtdc.in/serviceableDelivery?
  servlet:
    context-path: /api/v1/
